version: '2'
services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    mem_limit: 512m
    cpus: 1
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - nfs_data_config:/config
      - nfs_data_shows:/tv
      - nfs_data_movies:/movies
    ports:
      - 6767:6767
    restart: unless-stopped
volumes:
  nfs_data_movies:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/Data/Movies
  nfs_data_shows:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/Data/Shows
  nfs_data_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/Data/Portainer/bazarrConfig
