version: "3.3"
services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - nfs_data_config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
    restart: unless-stopped
  volumes:
  nfs_data_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/Data/Portainer/homepageConfig
