version: '2'
services:
  transmission:
    image: haugene/transmission-openvpn
    cap_add:
      - NET_ADMIN
    restart: always
    ports:
      - "9091:9091"
    volumes:
      - nfs_data_config:/config # where transmission-home is stored
      - nfs_data_config:/data # where transmission will store the data
      - nfs_data_download:/downloads
      - nfs_data_watch:/watch
    environment:
      - PUID=1000
      - PGID=1000
      - TRANSMISSION_DOWNLOAD_DIR=/downloads/complete
      - TRANSMISSION_INCOMPLETE_DIR=/downloads/incomplete
      - WATCH_DIR_ENABLED=true
      - TRANSMISSION_WATCH_DIR_FORCE_GENERIC=true
      - TRANSMISSION_WATCH_DIR=/watch
      - OPENVPN_PROVIDER=PROTONVPN
      - OPENVPN_USERNAME=${USERNAME}
      - OPENVPN_PASSWORD=${PASSWORD}
      - OPENVPN_CONFIG=Netherlands 
      - OPENVPN_CONFIG=nl.protonvpn.net.udp # https://github.com/haugene/vpn-configs-contrib/tree/main/openvpn/protonvpn
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - LOCAL_NETWORK=192.168.1.0/24
volumes:
  nfs_data_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/Data/Portainer/transmissionConfig
   nfs_data_download:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/Data/Transmission/Downloads
   nfs_data_watch:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/Data/Transmission/Watch
